### PR TITLE
add slides to web-page

### PR DESCRIPTION
**Pull request by stemangiola**

### CODE REVIEW

**Review by mblue9 — APPROVED** [review]
Can you change the name of the image or where it's referenced in the vignette as that's why it's failing the checks here
```
Quitting from lines 43-44 (tidytranscriptomics.Rmd) 
Error: processing vignette 'tidytranscriptomics.Rmd' failed with diagnostics:
Cannot find the file(s): "../inst/vignettes/tidybulkpipeline-01.png"
--- failed re-building ‘tidytranscriptomics.Rmd’
```

**Comment by mblue9** [comment]
Also cool that you did this that was quick!! Looking forward to seeing what it looks like.

**Comment by mblue9** [comment]
What about this.. did you want to change the name of the image file or where it's referenced in the vignette?
Am keen to see what the slides look like :)

**Comment by stemangiola** [comment]
> 
> 
> What about this.. did you want to change the name of the image file or where it's referenced in the vignette?
> Am keen to see what the slides look like :)

I see OK

**Comment by stemangiola** [comment]
Done. However I would consider whether we need that image since is duplicated in the background section.

**Comment by mblue9** [comment]
That's true. if we now have the background section then it's prob redundant to also put it in the workshop Rmd.

**Pull request merged**
