### PR TITLE
change survival column names

### PR DESCRIPTION
**Pull request by stemangiola**

### CODE REVIEW

**Review by mblue9 — COMMENTED** [review]
Great, I would use event_occurred ...what do you think?

**Comment by stemangiola** [comment]
for records

```
BRCA =
    readRDS("~/PhD/deconvolution/ARMET/dev/armet_BRCA_input.rds") %>% 
    nanny::nest_subset(data = -patient)  %>% nest(data2 = -alive) %>% 
    mutate(data2 = map(
        data2, 
        ~ .x %>% 
            dplyr::arrange(PFI.time.2) %>%
            dplyr::slice(c(1:5, (n()-5):n()) )
    )) %>% 
    unnest(data2) %>% 
    unnest(data) %>% 
    dplyr::select(patient, transcript, count, contains("PFI")) %>%
    mutate_if(is.character, as.factor) %>%
    mutate(PFI.2 = as.integer(PFI.2)) %>%
    dplyr::rename(time = PFI.time.2, event_occurred = PFI.2)
```

**Comment by mblue9** [comment]
Cool, could you add that info into data-raw folder like the pasilla.R?
https://github.com/stemangiola/rpharma2020_tidytranscriptomics/tree/master/data-raw
as that'll make it easier to find in the future if we need to

**Comment by mblue9** [comment]
Just fyi symbol isn't present because the object is being crated without it 

```
pasilla_de <- 
  rpharma2020tidytranscriptomics::pasilla %>% 
  
  # Convert SE object to tibble
  tidybulk %>%
  
   # Scale abundance for plotting
  identify_abundant(factor_of_interest=condition) 
```

You could use the `counts_filtered` instead that's further up in that Rmd as that has they symbol and then could remove the redundant code above. That code came from the main Rmd but is not needed in the solutions.Rmd.

**Pull request merged**
