### PR TITLE
first setup

### LINKED ISSUE #9: workshop polls

### PR DESCRIPTION
**Pull request by stemangiola**

### CODE REVIEW

**Comment by stemangiola** [comment]
Feel free to change, edit, move, add pools. This is just an example on how can be integrated with style in the document

**Comment by mblue9** [comment]
Cool looks good. 

I will change Pool to Poll. Pool means something different.

I was thinking we'd ask the polls after the Exercises sections but maybe we could also (or instead) ask them like you have here during the main material. 

Is temp.Rmd needed here or was that added by accident?

**Comment by stemangiola** [comment]
> Pool means something different.

Summer is coming!

**Comment by stemangiola** [comment]
> I was thinking we'd ask the polls after the Exercises sections but maybe we could also (or instead) ask them like you have here during the main material.

I was thinking it would be good to keep the audience connected and making it fun. Having said that I think at the time of the exercises is good too. I think making it as I did changes a lot the structure we agreed on. I leave to you the decision.


> Is temp.Rmd needed here or was that added by accident?

Accident :)

**Comment by mblue9** [comment]
>>Pool means something different.

>Summer is coming!

Hah yes well it seemed like it was yesterday 🌞 but not so much today ☁️ 

> I was thinking it would be good to keep the audience connected and making it fun. Having said that I think at the time of the exercises is good too. I think making it as I did changes a lot the structure we agreed on. I leave to you the decision.

I'm all for making it as fun as possible 😄 We could maybe have both - short polls during the material and then one after the exercises. I'll play around with the polls today and we can decide tomorrow where we think they fit best.

**Comment by stemangiola** [comment]
> 
> 
> > > Pool means something different.
> 
> > Summer is coming!
> 
> Hah yes well it seemed like it was yesterday 🌞 but not so much today ☁️
> 
> > I was thinking it would be good to keep the audience connected and making it fun. Having said that I think at the time of the exercises is good too. I think making it as I did changes a lot the structure we agreed on. I leave to you the decision.
> 
> I'm all for making it as fun as possible 😄 We could maybe have both - short polls during the material and then one after the exercises. I'll play around with the polls today and we can decide tomorrow where we think they fit best.

Thinking about it I think it would be beneficial to integrate the (easy) exercises within the material, it would also allow for a better rhythm of the workshop, and let us breathe a bit more.

**Comment by mblue9** [comment]
>Thinking about it I think it would be beneficial to integrate the (easy) exercises within the material, it would also allow for a better rhythm of the workshop, and let us breathe a bit more.

Yes agree, I've added a couple of easy poll questions for Part 1 so far. Are you thinking we still do a poll after the Exercises section for a longer pause? I've done that here for the moment but can change.

**Comment by stemangiola** [comment]
> 
> 
> > Thinking about it I think it would be beneficial to integrate the (easy) exercises within the material, it would also allow for a better rhythm of the workshop, and let us breathe a bit more.
> 
> Yes agree, I've added a couple of easy poll questions for Part 1 so far. Are you thinking we still do a poll after the Exercises section for a longer pause? I've done that here for the moment but can change.

I don't have strong opinion about that. Nonetheless, I think a pause is nice between each section.

**Comment by mblue9** [comment]
>I don't have strong opinion about that. Nonetheless, I think a pause is nice between each section.

Ok let's leave in it for the moment then. It also gives a chance to have a longer pause to answer questions after the Part. Also might be good as a connecting transition to have them start working on the pasilla dataset in the Part 1 exercises as we're switching from airway to using pasilla in Part 2.

**Comment by mblue9** [comment]
Do you know why I get this warning here?
You didn't with your initial PR here.

```
--- re-building ‘tidytranscriptomics.Rmd’ using rmarkdown
Warning in get_engine(options$engine) :
  Unknown language engine 'poll_1' (must be registered via knit_engines$set()).
Warning in get_engine(options$engine) :
  Unknown language engine 'poll_2' (must be registered via knit_engines$set()).
Warning in get_engine(options$engine) :
  Unknown language engine 'poll_3' (must be registered via knit_engines$set()).
Warning in get_engine(options$engine) :
  Unknown language engine 'poll_4' (must be registered via knit_engines$set()).
```

**Comment by mblue9** [comment]
Seems that warning is not important as it doesn't appear if I fix the unrelated dplyr::count error.
I'll merge this and then we can make more changes as needed.
I think the Part 2 questions might be a bit hard for during the material, maybe better at the end of Part 2 if we can come up with a couple of easier ones for during Part 2.

**Pull request merged**
